
##ICI scores


# Load Functions for ICI score from Kens paper 

```{r}
#####################################################################################
#
# Identity
#
# Calculate Index of Cell Identity (ICI)
#
#  Idan Efroni (ie10@nyu.edu)
#  Dec  14th, 2014
#####################################################################################

# Number of permuations used to calculate significance
RAND_ITER=1000

# The minimal Spec score that can be used as a marker
MIN_USEFUL_SPEC= 0.15

#  Arguments
#    cell - vector of gene expression values
#    ci_for_mark - spec scores for the markers
#    markers - list of markers from getMarkerList

getIdentityScore(gene_expression_matrix,1,ci_for_marks, marker_gene_names)

getRandomBackground <- function(data, cell, ci_for_mark, marker_num) {

	rand_id_scores=vector()
	for(i in 1:RAND_ITER) {
		# get marker set
	  ## grabs random ATGs from cell of same length as marker set
		### mixes up the oder of the weights
	  marker_set_n = sample(1:nrow(data), marker_num)
	  marker_set <- rownames(data)[marker_set_n]
		rand_id_scores[i] = getIdentityScore(data,cell, ci_for_mark, marker_set)
	}
	rand_id_scores[is.na(rand_id_scores)]=0
	rand_id_scores
}



getIdentityScore <- function(data, cell, ci_for_mark, markers){
  mean(data[markers,cell]* ci_for_mark) * ((sum(data[markers,cell]>0))/length(markers))
}
#####################################################################################
#
#  getIdentity
#
#  returns ICIs for a data matrix
#
#  Arguments
#    data - gene expression matrix
#    ci - spec data structure
#    markers - list of markers from getMarkerList
#    returnSig - should significance be calculated
#    universe - what subset of genes should be used for randomizations

getIdentity <- function(data, ci, returnSig=FALSE, universe=c()) {

	hs_scoremat <- matrix(nrow=ncol(data), ncol=ncol(ci))

	colnames(hs_scoremat) <- colnames(ci)
	rownames(hs_scoremat) <- colnames(data)
	calls <- hs_scoremat
	sig <- calls
	#all_markers = unlist(markers)

	for(cell in 1:nrow(hs_scoremat)) {
		markers_cell = data[, cell]
		#head(print(markers_cell))
		for(marker_number in 1:ncol(ci)) {
			#print(marker_number)
      tissue_markers <- which(ci[,marker_number] > 0)
      ci_for_marks <- ci[tissue_markers,marker_number]
      marker_gene_names <- rownames(ci)[tissue_markers]
      
		  hs_scoremat[cell, marker_number] = getIdentityScore(data ,cell ,ci_for_marks, marker_gene_names)
		  calls[cell, marker_number] = sum(data[marker_gene_names,cell]>0)
			if(returnSig) {
			  sig[cell,marker_number] <- 1-which(order(c(hs_scoremat[cell,marker_number], getRandomBackground(data, cell ,ci_for_marks, length(marker_gene_names))))==1)/(RAND_ITER+1)
			}
		}
	}
  print(hs_scoremat)
	hs_scoremat_norm <- hs_scoremat
	for(i in 1:nrow(hs_scoremat_norm)) { hs_scoremat_norm[i,] = hs_scoremat_norm[i,]/sum(hs_scoremat_norm[i,]) }
	hs_scoremat_norm[is.nan(hs_scoremat_norm)]=0
	if(returnSig) {
		list(hs_scoremat_norm, hs_scoremat, calls, sig, matrix(nrow=nrow(sig), ncol=ncol(sig), p.adjust(sig, "BH")))
	} else {
		list(hs_scoremat_norm, hs_scoremat)
	}
}

#i2 <- getIdentity(v,markers)
### NEED TO USE A MERGED LIST FOR MARKERS OTHERWISEWILL GET ONLY NAs and will do math wrong
d <- merge(gene_expression_matrix, ci,by.x = 0, by.y = 0)
merged_ci <- d[,399:413]
rownames(merged_ci) <- d$Row.names

#d <- inner_join(ci,gene_expression_matrix,by = 0 )
i3 <- getIdentity(gene_expression_matrix,merged_ci,returnSig=TRUE)
```



# my function re-writen for my data
```{r}


getIdentity <- function(data, ci, random){
  d <- merge(data, ci,by.x = 0, by.y = 0)
  ### make data matrix of cells X tissue_types 
  hs_scoremat <- matrix(nrow=ncol(data), ncol=ncol(ci))
  colnames(hs_scoremat) <- colnames(ci)
	rownames(hs_scoremat) <- colnames(data)
  #for each cell
  for(n_cell in 1:ncol(data)){
    ### for each marker
    for(n_marker in 1:ncol(ci)){
      cell =  d[,n_cell+1]
      marker = d[,(n_marker + ncol(data))+1] ### if I mix these the same 15 will still be expressed but on different genes
      number_of_tissue_markers <- sum(ci[,n_marker] > 0)
      
      
      ici_scores <- cell * marker
      number_of_expressed_tissue_markers <- sum(ici_scores > 0)
      cell_ici = sum(ici_scores)/number_of_tissue_markers * (number_of_expressed_tissue_markers/number_of_tissue_markers)
      ### double check this is what they are doing in there code....
      ### this is inncorrect should be not the number of expressed genes but number of expressed markers for that tissue
      
      Random_one
      marker = d[,(n_marker + ncol(data))+1] ### if I mix these the same 15 will still be expressed but on different genes
      ### different 15 genes chossen as markers from anywhere in population
      ### Then the ci for that mark for that tissue type needs to be choosen
      ### prob need to rewrite code so it is more simlar to theirs
      ### how do i mutiple based on row names...gene_expression_matrix[c("AT1G01010","AT1G01020"),1]
      marker_number = 5
      tissue_markers <- which(markers[,marker_number] > 0)
      ci_for_marks <- markers[tissue_markers,marker_number]
      marker_gene_names <- rownames(markers)[tissue_markers]
      cell_m <- gene_expression_matrix[marker_gene_names,1]
      
      ci_for_marks * cell_m
      ## remove NAs and then take the mean...
      ## total number of tissue markers should not or should include NAs? Not sure...
      ci_for_marks <- markers[tissue_markers,5]
                ici_scores <- d[,n_cell+1][c(ranomints of same length)] * d[,(n_marker + ncol(data))+1]

  }
    }
  return(hs_scoremat)
}



getIdentityScore <- function(cell, ci_for_mark, markers){
	mean(cell[markers]* ci_for_mark) * ((sum(cell[markers]>0))/length(markers))
}


getRandomBackground <- function(cell, ci_for_mark, universe, marker_num) {

	rand_id_scores=vector()
	cell = cell[universe]

	for(i in 1:RAND_ITER) {
		# get marker set
	  ## grabs random ATGs from cell of same length as marker set
		### mixes up the genes for the marker set for that tissue
	  marker_set = sample(1:length(cell), marker_num)
		rand_id_scores[i] = getIdentityScore(cell, ci_for_mark, marker_set)
	}
	rand_id_scores[is.na(rand_id_scores)]=0
	rand_id_scores
}
		
		


```
### load data
# merged
```{r}

library(Seurat)
library(cowplot)
library(Matrix)

merged.data <- read.csv("induced_uninduced_merged.dge.csv",sep=',', row.names = 'GENE')
head(merged.data)
meta.data <- read.csv("metadata.csv",sep=',', row.names = 'CELL')
head(meta.data)
merged <- CreateSeuratObject(raw.data = merged.data, min.cells = 3, min.genes = 200, project = "4000_ATHA", meta.data = meta.data)
#QC + Normalization
#merged <- SubsetData(merged, subset.name = "nGene", accept.high = 12000)
merged <- NormalizeData(object = merged, normalization.method = "LogNormalize", scale.factor = 1e4)
```

# unmerged

```{r}
vnd7.data <- read.csv("star_gene_exon_tagged.clean_at_199cells_induced.dge.csv",sep=',', row.names = 'GENE')
head(vnd7.data)
vnd7 <- CreateSeuratObject(raw.data = vnd7.data)
vnd7 <- SubsetData(vnd7, subset.name = "nGene", accept.high = 12000)
vnd7 <- NormalizeData(object = vnd7, normalization.method = "LogNormalize", scale.factor = 1e4)


wt.data <- read.csv("star_gene_exon_tagged.clean_at_198cells_uninduced.dge",sep=',', row.names = 'GENE')
head(wt.data)
wt <- CreateSeuratObject(raw.data = wt.data)
wt <- SubsetData(wt, subset.name = "nGene", accept.high = 12000)
wt <- NormalizeData(object = wt, normalization.method = "LogNormalize", scale.factor = 1e4)
```




### My code for generating ICI scores

```{r}
gene_expression_matrix <- as.data.frame(as.matrix(merged@data))
ci <- read.csv("spec_scores.csv", row.names="Locus")
markers <- read.csv("markers.csv",row.names="Locus")
universe = rownames(gene_expression_matrix)

# can use mean if mean kepts all the scores

i <- getIdentity(gene_expression_matrix,ci)
summary(i)

library("pheatmap")
library("RColorBrewer")

mat_row <- data.frame(group = meta.data$STATE)
rownames(mat_row) <- rownames(i)

mat_colors <- list(group = brewer.pal(2, "Set1"))
names(mat_colors$group) <- unique(meta.data$STATE)

pheatmap(i, show_rownames=FALSE,   annotation_row= mat_row,
  annotation_colors = mat_colors, border_color= NA, main="Merged Data")

library(reshape)
rownames(i) <- meta.data$STATE
x <- melt(i)
colnames(x) <- c("state","tissue","ICI")
#rownames(x) <- rownames(gene_expression_matrix)
ggplot(x, aes(tissue, ICI, color= state)) + geom_boxplot() + theme(axis.text=element_text(size=10, angle = 60), axis.text.y = element_blank())


## each cell.. uninduced 100% idendity what number are there of cells of each type
## number of cells that mixed cell id..
## merstmatic and mature xylem cell propotios...
#3 give list of 
```

## testing each tissue type
```{r}

w <- as.data.frame(as.matrix(wt@data))
v <- as.data.frame(as.matrix(vnd7@data))

i <- getIdentity(w,ci)
i2 <- getIdentity(v,markers)

breaksList = seq(0, 0.2, by = 0.001)
pheatmap(i,breaks=breaksList, color=colorRampPalette(brewer.pal(9,"Blues"))(200))
pheatmap(i2, breaks=breaksList,color=colorRampPalette(brewer.pal(9,"Blues"))(200))



wt <- melt(i)
oe <- melt(i2)
colnames(wt) <- c("cell","tissue","value")
colnames(oe) <- c("cell","tissue","value")

ggplot(oe, aes(tissue, cell)) + geom_tile(aes(fill = value,vjust=TRUE)) + theme(axis.text=element_text(size=10, angle = 60), axis.text.y = element_blank())

ggplot(wt, aes(tissue, cell)) + geom_tile(aes(fill = value,vjust=TRUE)) + theme(axis.text=element_text(size=10, angle = 60), axis.text.y = element_blank())

ggplot(oe, aes(tissue,value, color=tissue)) + geom_boxplot() +theme(axis.text=element_text(size=10, angle = 60), axis.text.y = element_blank())

ggplot(wt, aes(tissue,value, color=tissue)) + geom_boxplot() +theme(axis.text=element_text(size=10, angle = 60), axis.text.y = element_blank())

```

## There is a correlation between VND7 expression and protoxylem ICI score 

```{r}                                                    
pci <- read.csv("Protoxylem.csv", row.names = "Locus")
l <- data.frame(markers[,8])
rownames(l) <- rownames(markers)
colnames(l) <- c("Protoxylem")

getOneIdentity <- function(data, spec){
  d <- merge(data, spec,by.x = 0, by.y = 0)
  ici_scores <- vector()
  for(n_cell in 1:ncol(data)){
      number_of_tissue_markers <- sum(spec$Protoxylem > 0)
      number_of_expressed_markers <- sum(d[,n_cell+1] > 0)
      print(n_cell)
      cell_ici = sum(d[,n_cell+1] * d$Protoxylem)/number_of_tissue_markers * (number_of_expressed_markers/number_of_tissue_markers) 
      ici_scores[n_cell] <- cell_ici
  }
  return(ici_scores)
}

proto <- getOneIdentity(gene_expression_matrix,l)
summary(proto)

y <- data.frame(as.numeric(as.matrix(merged@data["AT1G71930",])),proto)
colnames(y) <- c("vnd7","xylem")
cor(y$vnd7,y$xylem)
ggplot(data = y, aes(vnd7,xylem)) + geom_point()

x <- data.frame(as.numeric(as.matrix(merged@data["AT1G71930",])),data.frame(as.numeric(as.matrix(merged@data["AT5G12870",]))))
                                                                                  
d <- data.frame(x, proto)
colnames(d) <- c("v","myb","value")
ggplot(data = d, aes(v,myb,color=value)) + geom_jitter()

```
### ICI for clusters
```{r}
ci <- read.csv("spec_scores.csv", row.names="Locus")
cluster.markers <- read.table("all_markers_merged.txt", header = TRUE)
cluster_0 <- subset(cluster.markers, cluster == 0)
cluster_1 <- subset(cluster.markers, cluster == 1)
cluster_2 <- subset(cluster.markers, cluster == 2)
cluster_3 <- subset(cluster.markers, cluster == 3)
cluster_4 <- subset(cluster.markers, cluster == 4)
cluster_5 <- subset(cluster.markers, cluster == 5)
cluster_6 <- subset(cluster.markers, cluster == 6)
cluster_7 <- subset(cluster.markers, cluster == 7)
cluster_8 <- subset(cluster.markers, cluster == 8)

getClusterIdentity <- function(cluster, ci){
  d <- merge(cluster, ci,by.x = "gene", by.y = 0)
  for(n_marker in 1:ncol(ci)){
      number_of_tissue_markers <- nrow(d)
      number_of_expressed_markers <- length(cluster)
      cell_ici = sum(d$avg_diff * d[,n_marker + ncol(cluster)])/number_of_tissue_markers * number_of_tissue_markers/number_of_expressed_markers
    print(colnames(ci)[n_marker])
    print(cell_ici)
    }
}

getClusterIdentity(cluster_0,ci)
getClusterIdentity(cluster_1,ci)
getClusterIdentity(cluster_2,ci)
getClusterIdentity(cluster_3,ci)
getClusterIdentity(cluster_4,ci)
getClusterIdentity(cluster_5,ci)
getClusterIdentity(cluster_6,ci)
getClusterIdentity(cluster_7,ci)
getClusterIdentity(cluster_8,ci)

```


```{r}

x <- data.frame(vnd7@data["AT1G71930",],vnd7@data["AT5G12870",])
colnames(x) <- c("v","myb")
oe_proto <- subset(oe,tissue="Protoxylem")

d <- merge(x, oe_proto,by.x = 0, by.y = "cell")

ggplot(data = d, aes(v,myb,color=value)) + geom_jitter()
ggplot(data = d, aes(v,value,color=value)) + geom_jitter()
cor(d$v,d$value)
```
